(function initDay4Story(global) {
  "use strict";

  const records = global.ClueRecords || (typeof module === "object" && module.exports ? require("./clue-records.js") : null);
  if (!records) throw new Error("ClueRecords must load before Day4Story");
  const day3Story = global.Day3Story || (typeof module === "object" && module.exports ? require("./day3-story.js") : null);
  if (!day3Story) throw new Error("Day3Story must load before Day4Story");

  const CLUES = Object.freeze({
    auditRequest: records.get("d4_audit_request"),
    verifiedRetention: records.get("d4_verified_retention"),
    evidenceSubmission: records.get("d4_evidence_submission"),
  });
  const ROOMS = day3Story.ROOMS;
  const previousMessages = Object.freeze(day3Story.MESSAGES.map((message) => Object.freeze({ ...message })));
  const MESSAGES = Object.freeze([
    ...previousMessages,
    { id: "d4-boss-recording", room: "boss", at: "day4BossCall", sender: "박태식 부장", text: "녹음 지원 인원 두 명 바로 이동해. 시작 시각은 9시 30분이야.", day: 4, time: "08:48" },
    { id: "d4-harin-studio", room: "harin", at: "day4HarinReady", sender: "서하린 사수", text: "공유 폴더 최종본과 기록 양식부터 받아 둬요. 이동하면서 확인할게요.", day: 4, time: "08:50" },
    { id: "d4-harin-audit", room: "harin", at: "day4AuditExplain", sender: "서하린 사수", text: "보안 감사 로그에서는 자동화 실행을 실제로 요청한 계정을 확인해야 해요.", day: 4, time: "11:43" },
    { id: "d4-pt-evidence", room: "pt", at: "day4EvidenceBrief", sender: "박태식", text: "제출용 근거 자료도 발표 자료와 함께 제출해.", day: 4, time: "13:35" },
    { id: "d4-pt-submit", room: "pt", at: "day4Submit", sender: "한도윤", text: "발표 자료와 제출용 근거 자료 모두 18.4%로 제출 완료했습니다.", day: 4, time: "17:08" },
    { id: "d4-harin-overtime", room: "harin", at: "day4FailureMessage", sender: "서하린 사수", text: "아직 회사죠? 확인 끝나면 더 붙잡혀 있지 말고 바로 퇴근해요. 내일 봐요.", day: 4, time: "19:18" },
  ]);

  const scenes = Object.freeze([
    { id: "day4Intro", time: "08:47", speaker: "시스템", text: "DAY 4\n발표 전날", location: "게임사업실 · 오전", visual: "출근 직후의 게임사업실. 도윤과 하린의 자리 위에 발표 자료가 열려 있다.", bgAssetId: "background.office.day", bgm: "daily" },
    { id: "day4BossCall", time: "08:48", speaker: "박태식", text: "옆 프로젝트 녹음이 오늘 오전으로 당겨졌어. 오디오 검수 담당이 갑자기 빠졌고, 외부 성우는 오전밖에 시간이 없어.", visual: "박태식이 시계를 확인하며 급히 녹음 지원 일정을 전달한다.", bgAssetId: "background.office.day", characters: [{ id: "boss", assetId: "character.boss.holding_cup.concerned", position: "right" }], activeCharacter: "boss", urgent: "strong", motion: "determined", camera: "impact", notification: "d4-boss-recording" },
    { id: "day4RoleAssign", time: "08:48", speaker: "박태식", text: "하린은 원고와 게임 용어 확인, 도윤은 테이크 번호와 수정 요청 기록. 녹음 시작은 9시 30분이야. 9시 20분까지 부스에 들어가.", visual: "박태식이 두 사람에게 역할과 마감 시각을 빠르게 나눠 준다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }] },
    { id: "day4PtConcern", time: "08:49", speaker: "한도윤", text: "저희 발표 자료 확인은 어떻게 합니까? 오늘 안에 제출용 근거 자료까지 준비해야 합니다.", visual: "도윤이 열어 둔 발표 자료 화면과 시계를 번갈아 확인한다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }] },
    { id: "day4BossDeadline", time: "08:49", speaker: "박태식", text: "오전 반나절 빠진다고 무너질 자료면 내일 발표도 못 해. 녹음이 한 테이크라도 밀리면 다음 예약까지 기다려야 하니까 지금 움직여.", visual: "박태식이 부스 예약표를 가리키며 즉시 출발하라고 재촉한다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }] },
    { id: "day4HarinReady", time: "08:50", speaker: "서하린", text: "제가 원고 버전을 확인할게요. 도윤 씨는 공유 폴더의 최종본과 기록 양식부터 내려받아요. 이동하면서 파일명 규칙 알려드릴게요.", visual: "하린이 원고와 헤드폰을 챙기고 도윤에게 바로 이동하자는 손짓을 한다.", bgAssetId: "background.office.day", characters: [{ id: "boss", assetId: "character.boss.holding_cup.concerned", position: "left" }, { id: "harin", assetId: "character.harin.arms_folded.concerned", position: "right" }], activeCharacter: "harin", notification: "d4-harin-studio" },
    { id: "day4StudioArrival", time: "09:17", speaker: "한도윤", text: "녹음실은 처음이네… 생각보다 안이 좁군.", location: "사내 녹음실 · 부스", visual: "방음문을 열고 처음 녹음 부스 안으로 들어선 도윤과 하린.", bgAssetId: "background.recording_booth.day", characters: [{ id: "harin", assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }], bgm: "recordingStudio" },
    { id: "day4StudioQuestion", time: "09:18", speaker: "한도윤", text: "선배는 녹음실에 오신 적 있으세요?", visual: "낯선 장비를 둘러보던 도윤이 하린에게 묻는다.", bgAssetId: "background.recording_booth.day", characters: [{ id: "harin", assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }] },
    { id: "day4StudioAnswer", time: "09:19", speaker: "서하린", text: "몇 번 있어요. 이벤트 대사 검수할 때 들어왔었어요. 장비 이름을 전부 외울 필요는 없고, 지금 들리는 소리와 테이크 번호만 맞추면 돼요.", dynamic: "studioAnswer", visual: "하린이 익숙하게 모니터링 장비를 확인하고 도윤에게 기록 방법을 설명한다.", bgAssetId: "background.recording_booth.day", characters: [{ id: "harin", assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }], activeCharacter: "harin" },
    { id: "day4MoveStudio", time: "09:20", speaker: "서하린", text: "문서로 설명하는 것보다 직접 듣는 게 빨라요. 이 헤드폰 쓰세요. 모니터 단자가 한쪽에 모여 있어서 조금 가까이 앉아야 해요.", location: "사내 녹음실 · 부스", visual: "하린이 도윤에게 별도의 모니터링 헤드폰을 건네고 자신의 헤드폰도 장비에 연결한다.", bgAssetId: "background.recording_booth.day", cgAssetId: "event_cg.day4.harin_headphone_handoff", cgTitle: "서하린이 건넨 헤드폰", cinematicDelay: 1800, bgm: "recordingStudio" },
    { id: "day4HeadphoneChoice", time: "09:21", speaker: "한도윤", text: "각자 쓴 헤드폰 선이 같은 모니터링 장비에 연결되면서 하린과 어깨가 가까워졌다. 뭐라고 할까?", visual: "좁은 녹음 부스에서 각자의 헤드폰을 쓰고 나란히 모니터링하는 두 사람.", bgAssetId: "background.recording_booth.day", characters: [{ id: "harin", assetId: "character.harin.relaxed_standing.embarrassed", position: "right" }], motion: "embarrassed", camera: "romance", choiceKey: "headphoneResponse", choices: [
      { id: "matchPace", text: "“너무 가까우면 불편하실 수 있으니, 괜찮은 거리인지 먼저 말씀해 주세요.”", delta: { trust: 1 }, replySpeaker: "서하린", reply: "먼저 물어봐 줘서 고마워요. 지금 거리는 괜찮으니 이대로 들어요." },
      { id: "yieldHeadphone", text: "“듣기 전에 좌우 채널과 음량부터 맞추겠습니다.” 모니터 수치를 확인한다.", delta: { work: 1 }, replySpeaker: "서하린", reply: "좋아요. 레벨을 먼저 맞추면 테이크 비교도 훨씬 정확해져요." },
      { id: "untangleTogether", text: "“같은 소리를 나란히 듣고 있으니 생각보다 든든하네요.” 살짝 웃는다.", delta: { affection: 1 }, replySpeaker: "서하린", reply: "도윤 씨도 참… 그래도 둘이 같이 들으니 놓치는 부분은 없겠네요." },
    ] },
    { id: "day4GuideRecording", time: "09:43", speaker: "한도윤", text: "왜 제가 가이드 대사를 읽는 겁니까?", location: "사내 녹음실 · 부스", visual: "스탠드 마이크 앞에 선 도윤과 옆에서 원고를 든 하린.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4MicShare", time: "09:47", speaker: "서하린", text: "성우분이 오시기 전에 문장 길이와 호흡을 확인하려는 거예요. 도윤 씨는 표시한 부분만 편하게 읽으면 돼요.", visual: "하린이 원고의 호흡 표시를 짚으며 가이드 녹음 방법을 설명한다.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4MicSmallTalk", time: "09:48", speaker: "한도윤", text: "선배가 옆에서 맞춰 주니까 생각보다 덜 긴장되는군요.", visual: "테이크가 끝난 줄 알고 마이크 앞에서 짧게 이야기를 나누는 두 사람.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.embarrassed", position: "right" }], motion: "embarrassed", camera: "romance" },
    { id: "day4MicChoice", time: "09:49", speaker: "한도윤", text: "테이크가 끝난 뒤에도 마이크가 계속 켜져 있어 방금 나눈 대화까지 녹음됐다. 어떻게 할까?", visual: "녹음 표시등이 켜진 마이크와 동시에 굳은 두 사람.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.embarrassed", position: "right" }], motion: "surprised", camera: "impact", effect: "mic-live", choiceKey: "micResponse", choices: [
      { id: "keepTake", text: "“대화가 자연스러웠으니 참고용으로 남겨도 되지 않을까요?”라고 한다.", delta: { affection: -1 }, replySpeaker: "서하린", reply: "제 동의 없이 사적인 대화를 남기는 건 싫어요. 방금 구간은 바로 지워 주세요." },
      { id: "checkLevels", text: "즉시 녹음을 정지하고 해당 구간을 표시한 뒤 새 테이크 번호를 만든다.", delta: { work: 1 }, replySpeaker: "서하린", reply: "처리가 빠르네요. 새 번호로 레벨부터 다시 맞추면 되겠어요." },
      { id: "apologize", text: "“방금 구간은 바로 삭제할까요?” 하린의 의사를 먼저 확인한다.", delta: { trust: 1 }, replySpeaker: "서하린", reply: "네, 삭제해 주세요. 먼저 물어봐 줘서 고마워요." },
    ] },
    { id: "day4HarinPast", time: "10:30", speaker: "서하린", text: "예전에는 이벤트 대사 정리하는 걸 좋아했어요. 짧은 문장 하나로 캐릭터가 달라지는 게 재미있었거든요.", visual: "원고의 감정 표시를 고치는 하린. 평소보다 편안한 표정이다.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }] },
    { id: "day4LastTake", time: "11:18", speaker: "서하린", text: "테이크 시각 바로 찾은 건 좋았어요. 처음인데도 기록을 제대로 남겼네요.", dynamic: "lastTake", visual: "케이블 잡음이 난 시각을 찾아 마지막 재녹음을 끝낸 두 사람.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }] },
    { id: "day4StudioWrapUp", time: "11:20", speaker: "서하린", text: "수고했어요. 성우님 녹음도 끝났으니 우리도 정리하고 올라가죠.", visual: "정리를 마친 두 사람이 헤드폰을 내려놓고 부스를 나설 준비를 한다.", bgAssetId: "background.recording_booth.day", characters: [{ assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }] },
    { id: "day4ReturnWalk", time: "11:35", speaker: "한도윤", text: "부스를 나서자마자 즐거웠던 공기는 가라앉고, 어제 미뤄둔 문서 이야기가 다시 떠올랐다.", visual: "복도를 걸으며 표정이 다시 진지해지는 도윤.", location: "사내 녹음실 · 복도", bgAssetId: "background.recording_booth.day" },
    { id: "day4ReturnPrompt", time: "11:41", speaker: "서하린", text: "자, 그럼 어제 보던 것부터 다시 이어가죠.", location: "게임사업실 · 오전", visual: "자리로 돌아온 하린이 어제 열어 두었던 문서 이력 화면을 다시 띄운다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }], bgm: "mystery" },
    { id: "day4Return", time: "11:42", speaker: "한도윤", text: "문서가 바뀐 시각과 내용은 확인했습니다. 이제 누가 자동화를 요청했는지 보면 되는 겁니까?", location: "게임사업실 · 오전", visual: "회사로 돌아와 보안 감사 화면을 연 도윤과 하린.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }] },
    { id: "day4AuditExplain", time: "11:43", speaker: "서하린", text: "네. 실제로 자동화를 실행해 달라고 요청한 계정은 보안 감사 로그에서 확인해야 해요.", bgAssetId: "background.office.day", characters: [{ id: "harin", assetId: "character.harin.arms_folded.concerned", position: "right" }], activeCharacter: "harin", motion: "determined", camera: "tension", system: { title: "SECURITY AUDIT", rows: ["문서 변경 이력 · 변경 시각과 내용", "보안 감사 로그 · 실제 요청 계정", "현재 상태 · 열람 권한 없음"] }, notification: "d4-harin-audit" },
    { id: "day4AuditRequest", time: "13:20", speaker: "시스템", text: "보안 감사 로그 조회 요청이 접수되었습니다.", location: "게임사업실 · 오후", visual: "점심 이후 도착한 감사 로그 조회 접수 알림.", bgAssetId: "background.office.day", system: { title: "AUDIT REQUEST", rows: ["상태 · 담당자 확인 대기", "목적 · 자동화 실행 요청 계정 확인"] }, clue: CLUES.auditRequest, bgm: "mystery" },
    { id: "day4EvidenceBrief", time: "13:35", speaker: "박태식", text: "평가위원이 수치 근거를 바로 열어 볼 수 있게 제출용 근거 자료도 같이 준비해.", visual: "박태식이 평가 시스템의 제출 항목을 가리킨다.", bgAssetId: "background.office.day", characters: [{ id: "boss", assetId: "character.boss.holding_cup.concerned", position: "right" }], activeCharacter: "boss", notification: "d4-pt-evidence" },
    { id: "day4VerifyMetric", time: "14:00", speaker: "서하린", text: "수치만 적지 말고 대상과 기간도 같이 남겨요. 같은 이름의 지표라도 기준이 다르면 다른 숫자가 될 수 있으니까요.", visual: "DAY 1 원본과 DAY 2 확인 기록을 나란히 비교하는 화면.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }], system: { title: "7일 차 잔존율 확인 결과", rows: ["현재 확인값 · 18.4%", "분석 대상 · 신규 가입 사용자", "분석 기준 · 가장 최근 자료 가입자", "확인 결과 · 원본과 계산 결과 일치"] }, clue: CLUES.verifiedRetention, bgm: "mystery" },
    { id: "day4EvidenceChoice", time: "14:20", speaker: "한도윤", text: "평가위원에게 가장 먼저 보여 줄 근거를 정하자.", visual: "원본 데이터, 계산식, 유저 조사 요약이 증빙 후보로 표시된다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }], choiceKey: "evidencePriority", choices: [
      { id: "sourceFirst", text: "정상 원본과 계산식을 첫 화면에 둔다.", delta: { work: 1, trust: 1 }, reply: "정상 원본과 계산식이 증빙 패키지의 첫 항목으로 배치됐다." },
      { id: "summaryFirst", text: "유저 조사 요약을 먼저 보여 준다.", delta: { affection: 0, work: 1 }, reply: "읽기는 쉬워졌지만 도윤은 원본 링크도 바로 다음에 배치했다." },
      { id: "criteriaFirst", text: "대상과 산정 기간을 먼저 설명한다.", delta: { trust: 1 }, reply: "같은 지표의 기준이 섞이지 않도록 산정 조건을 선명하게 표시했다." },
    ] },
    { id: "day4EvidencePreview", time: "14:45", speaker: "한도윤", text: "미리보기에도 18.4%로 표시됩니다. 계산식과 ‘신규유저 7일 차 잔존율 검증본’ 링크도 정상적으로 열립니다.", emphasis: ["18.4%", "7일"], visual: "제출용 근거 자료 미리보기. 모든 값이 정상으로 표시된다.", bgAssetId: "background.office.day", system: { title: "제출용 근거 자료", rows: ["발표 자료 수치 · 18.4%", "연결된 원본 · 7일 차 잔존율 검증본", "계산식 · (7일 차 잔존 유저 수) ÷ (신규 가입자 수) × 100", "계산 기준 · 가장 최근 자료 신규 가입자", "원본 링크 · 정상"] } },
    { id: "day4QuestionRehearsal", time: "15:20", speaker: "서하린", text: "제출 자료와 발표 자료의 값이 다르면요?", visual: "평가위원 역할을 맡아 질문하는 하린과 답변 기록을 든 도윤.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }] },
    { id: "day4QuestionAnswer", time: "15:21", speaker: "한도윤", text: "우선 산정 기준이 같은지 확인하고, 보존한 정상 원본과 제출 생성 기록을 비교하겠습니다.", visual: "도윤이 원본과 제출 기록을 순서대로 짚는다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }] },
    { id: "day4RehearsalSetup", time: "16:10", speaker: "박태식", text: "제출 자료는 정리됐지? 그럼 내일 들어가기 전에 한 번 맞춰 보자. 도윤이 처음부터 발표하고, 하린은 평가위원 역할 맡아.", location: "사내 회의실 · 오후", visual: "박태식이 회의실 화면 앞에서 발표 리허설의 역할을 나눈다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }], motion: "determined", camera: "reveal" },
    { id: "day4RehearsalRole", time: "16:10", speaker: "서하린", text: "제가 중간에 질문해도 되죠? 실제 평가라고 생각하고 끊어 볼게요.", visual: "서하린이 발표 자료를 훑으며 평가위원 역할을 준비한다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4RehearsalEvidence", time: "16:11", speaker: "박태식", text: "그래. 준비한 답만 하지 말고, 근거 자료를 바로 찾을 수 있는지도 보자.", visual: "박태식이 발표 자료 옆의 증빙 패키지를 가리킨다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }] },
    { id: "day4RehearsalReady", time: "16:11", speaker: "한도윤", text: "알겠습니다. 발표 화면과 증빙 패키지까지 열어 두겠습니다.", visual: "도윤이 발표 화면과 증빙 패키지를 나란히 준비한다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "left" }, { assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4RehearsalScreen", time: "16:12", speaker: "시스템", text: "최종 발표 자료와 확인된 제출용 근거 자료가 회의실 화면에 나란히 표시되었다.", visual: "최종 발표 자료와 제출용 근거 자료가 함께 열린 회의실 화면.", bgAssetId: "background.meeting_room.afternoon", system: { title: "신규 사용자 초반 경험 개선안", rows: ["현재 확인값 · 7일 차 잔존율 18.4%", "분석 대상 · 신규 가입 사용자", "근거 자료 · 연결 완료", "발표 준비 · 리허설 대기"] } },
    { id: "day4RehearsalStart", time: "16:12", speaker: "박태식", text: "좋아. 시간 잴 테니까 처음부터 시작해.", visual: "박태식이 시간을 확인하고 도윤에게 시작 신호를 보낸다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }] },
    { id: "day4RehearsalOpening", time: "16:13", speaker: "한도윤", text: "발표 시작하겠습니다. 이번 개선안의 핵심은 신규 사용자의 초반 이탈 구간을 줄이는 것입니다.", visual: "도윤이 첫 장을 띄우고 발표의 핵심 목표부터 설명한다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "left" }, { assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4RehearsalMetric", time: "16:14", speaker: "한도윤", text: "가장 최근 자료 기준으로 신규 가입자의 7일 차 잔존율은 18.4%입니다. 이 수치는 개선 효과가 아니라 지금 상태를 보여주는 확인값이고, 수치는 확인된 원본과 동일하며 분석 대상과 근거 자료도 함께 적었습니다.", visual: "핵심 수치와 계산 기준이 한 화면에 정리된 발표 슬라이드.", bgAssetId: "background.meeting_room.afternoon", system: { title: "현재 확인값", rows: ["7일 차 잔존율 · 18.4%", "분석 대상 · 신규 가입 사용자", "분석 기준 · 가장 최근 자료", "확인 결과 · 원본과 계산 결과 일치"] } },
    { id: "day4RehearsalQuestion", time: "16:15", speaker: "서하린", text: "질문하겠습니다. 발표 자료와 제출된 증빙의 수치가 다르게 보인다면, 어떤 자료를 기준으로 설명하시겠어요?", visual: "서하린이 평가위원처럼 발표의 수치 차이를 질문한다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4RehearsalAnswer", time: "16:16", speaker: "한도윤", text: "먼저 두 자료의 산정 대상과 기간이 같은지 확인하겠습니다. 이후 보존한 정상 원본과 제출 생성 기록을 비교해 어느 단계에서 차이가 생겼는지 설명하겠습니다.", visual: "도윤이 화면의 산정 기준과 제출 생성 기록을 차례로 가리킨다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "left" }, { assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4RehearsalFollowUp", time: "16:17", speaker: "서하린", text: "좋아요. 그러면 평가위원이 원본을 바로 보여 달라고 하면요?", visual: "서하린이 답변을 기록한 뒤 곧바로 추가 질문을 건넨다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4RehearsalEvidenceAnswer", time: "16:18", speaker: "한도윤", text: "증빙 패키지 첫 화면에서 정상 원본과 계산식을 열겠습니다. 말로 해명하기 전에 검증된 근거부터 제시하겠습니다.", visual: "도윤이 증빙 패키지의 정상 원본과 계산식 위치를 바로 열어 보인다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "left" }, { assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4Rehearsal", time: "16:19", speaker: "박태식", text: "수치 설명은 좋아. 그런데 앞부분이 길어. 결론부터 말하고, 질문이 들어오면 근거를 꺼내.", visual: "박태식이 발표 흐름을 짚으며 결론을 먼저 전달하라고 조언한다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }] },
    { id: "day4RehearsalCommit", time: "16:20", speaker: "한도윤", text: "네. 핵심 수치와 개선 방향을 먼저 전달하고, 산정 기준은 질의응답에서 설명하겠습니다.", visual: "도윤이 피드백을 반영해 발표 순서를 다시 정리한다.", bgAssetId: "background.meeting_room.afternoon", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "left" }, { assetId: "character.harin.relaxed_standing.neutral", position: "right" }] },
    { id: "day4Submit", time: "17:05", speaker: "시스템", text: "발표 자료와 제출용 근거 자료 제출이 완료되었습니다.", location: "게임사업실 · 오후", visual: "제출 완료 화면. 발표 자료와 근거 자료 모두 18.4%로 표시된다.", bgAssetId: "background.office.day", system: { title: "발표 자료 제출 완료", rows: ["발표 자료 수치 · 18.4%", "근거 자료 수치 · 18.4%", "원본 링크 · 정상", "제출 확인 · DAY 4 17:08"] }, clue: CLUES.evidenceSubmission, notification: "d4-pt-submit" },
    { id: "day4Preserve", time: "17:09", speaker: "서하린", text: "생성 번호와 확인 화면을 작업 기록에 남겨요. 내일 문제가 생겨도 우리가 무엇을 확인했는지는 증명할 수 있게요.", visual: "도윤이 제출 번호와 확인 시각을 별도 업무 기록에 보존한다.", bgAssetId: "background.office.day", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }] },
    { id: "day4LeaveLead", time: "17:30", speaker: "서하린", text: "오늘 확인한 상태만 보존하고 퇴근해요. 부장님이 다른 일을 붙이기 전에요.", dynamic: "leaveLead", location: "게임사업실 · 퇴근", visual: "노을이 비치는 사무실에서 퇴근 준비를 마친 두 사람과 멀리서 다가오는 박태식.", bgAssetId: "background.office.evening", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }], bgm: "minigame" },
    { id: "day4Escape", time: "17:31", speaker: "시스템", text: "박태식 부장에게 붙잡히기 전에 엘리베이터까지 이동하세요.", visual: "도윤의 SD풍 상상 속 사무실 탈출 경로. 추격 캐릭터 아트는 미니게임 도형으로 표시한다.", bgAssetId: "background.office.evening", startEscape: true },
    { id: "day4SuccessArrival", branch: "success", time: "17:40", speaker: "한도윤", dynamic: "escapeArrival", text: "도착했습니다. 이번에는 부장님께 붙잡히지 않았군요.", location: "엘리베이터 로비 · 퇴근", visual: "부장님의 시야를 벗어나 엘리베이터 앞에 도착한 도윤과 하린.", bgAssetId: "background.elevator_lobby.night", characters: [{ assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }], bgm: "harin" },
    { id: "day4SuccessDinnerInvite", branch: "success", time: "17:41", speaker: "서하린", text: "정말 제시간에 나왔네요. 저녁 약속 없으면 근처에서 같이 먹고 갈래요? 오늘은 우리 둘 다 제대로 먹은 게 없잖아요.", visual: "엘리베이터를 기다리며 하린이 조금 머뭇거리다 저녁을 제안한다.", bgAssetId: "background.elevator_lobby.night", characters: [{ assetId: "character.harin.relaxed_standing.embarrassed", position: "right" }], activeCharacter: "harin", motion: "embarrassed", camera: "romance" },
    { id: "day4SuccessDinnerArrival", branch: "success", time: "18:12", speaker: "한도윤", text: "좋습니다. 오늘은 선배가 자주 가는 곳으로 가죠.", location: "회사 근처 비스트로 · 저녁", visual: "퇴근한 두 사람이 푸른 저녁 도심이 보이는 조용한 비스트로에 마주 앉았다.", bgAssetId: "background.bistro.evening", effect: "dinner-evening", bgm: "harin" },
    { id: "day4SuccessDinnerTalk", branch: "success", time: "18:26", speaker: "서하린", dynamic: "dinnerConversation", visual: "따뜻한 조명 아래에서 업무 이야기가 조금씩 편한 대화로 바뀐다.", bgAssetId: "background.bistro.evening", characters: [{ assetId: "character.harin.relaxed_standing.gentle_smile", position: "right" }], activeCharacter: "harin", effect: "dinner-evening" },
    { id: "day4SuccessDinnerReply", branch: "success", time: "18:28", speaker: "한도윤", text: "오늘은 선배 덕분에 녹음도 발표 준비도 무사히 끝냈습니다. 다음에는 제가 먼저 저녁을 제안하겠습니다.", visual: "도윤이 평소보다 부드러운 표정으로 하린에게 감사를 전한다.", bgAssetId: "background.bistro.evening", characters: [{ assetId: "character.harin.relaxed_standing.embarrassed", position: "right" }], effect: "dinner-evening" },
    { id: "day4SuccessEnd", branch: "success", time: "19:05", speaker: "시스템", text: "DAY 4 완료\n정시 퇴근에 성공하고 서하린과 저녁을 함께했습니다.", location: "회사 근처 비스트로 · 저녁", visual: "식사를 마친 두 사람이 푸른 야경을 뒤로하고 내일 발표를 기약하며 자리에서 일어났다.", bgAssetId: "background.bistro.evening", effect: "dinner-evening", end: true, bgm: "daily" },
    { id: "day4FailureCaught", branch: "failure", time: "17:32", speaker: "박태식", text: "한도윤, 잠깐. 제출 패키지 생성 기록이랑 원본 링크 한 번만 더 맞춰 보고 가.", location: "게임사업실 · 퇴근", visual: "엘리베이터로 향하던 도윤을 박태식이 불러 세운다.", bgAssetId: "background.office.evening", characters: [{ assetId: "character.boss.holding_cup.concerned", position: "right" }], activeCharacter: "boss", motion: "determined", camera: "impact", bgm: "overtime" },
    { id: "day4FailureHarinLeaves", branch: "failure", time: "17:35", speaker: "서하린", text: "저 먼저 갈게요. 확인만 끝내고 너무 늦기 전에 퇴근해요. 내일 발표 전에 같이 다시 보면 되니까요.", visual: "하린이 걱정스러운 표정으로 도윤을 돌아본 뒤 먼저 사무실을 나선다.", bgAssetId: "background.office.evening", characters: [{ assetId: "character.harin.arms_folded.concerned", position: "right" }], activeCharacter: "harin" },
    { id: "day4FailureOvertime", branch: "failure", time: "19:05", speaker: "시스템", text: "추가 확인 업무가 예상보다 길어졌다. 사무실에는 도윤과 꺼지지 않은 모니터만 남았다.", location: "게임사업실 · 야근", visual: "불이 대부분 꺼진 야간 사무실에서 제출 기록을 다시 대조하는 도윤.", bgAssetId: "background.office.night", system: { title: "OVERTIME CHECK", rows: ["제출 패키지 · 재확인 완료", "원본 링크 · 정상", "추가 수정 · 없음", "현재 시각 · 19:05"] }, bgm: "overtime" },
    { id: "day4FailureMessage", branch: "failure", time: "19:18", speaker: "한도윤", text: "하린에게서 메시지가 도착했다. 오늘 저녁은 다음으로 미뤄야 할 것 같다.", visual: "야간 사무실 모니터 한쪽에 하린의 메시지 알림이 표시된다.", bgAssetId: "background.office.night", notification: "d4-harin-overtime" },
    { id: "day4FailureReply", branch: "failure", time: "19:20", speaker: "한도윤", text: "확인 마쳤습니다. 걱정하지 마시고 먼저 쉬십시오. 내일 뵙겠습니다.", visual: "도윤이 하린에게 답장을 보낸 뒤 마지막 확인 창을 닫는다.", bgAssetId: "background.office.night" },
    { id: "day4FailureEnd", branch: "failure", time: "19:30", speaker: "시스템", text: "DAY 4 완료\n정시 퇴근에는 실패했지만 추가 확인 업무를 마쳤습니다.", location: "게임사업실 · 야근", visual: "늦은 시간 홀로 사무실 불을 끄고 나서는 도윤.", bgAssetId: "background.office.night", end: true, bgm: "daily" },
  ]);

  function validateScenes(items) {
    const ids = new Set();
    const errors = [];
    items.forEach((scene, index) => {
      if (!scene.id || ids.has(scene.id)) errors.push(`invalid scene id at ${index}`);
      ids.add(scene.id);
      if (!scene.time || !scene.speaker) errors.push(`missing required field at ${scene.id || index}`);
    });
    return errors;
  }

  const api = Object.freeze({ scenes, CLUES, ROOMS, MESSAGES, validateScenes });
  if (typeof module === "object" && module.exports) module.exports = api;
  global.Day4Story = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
