const ASSET='assets/';
const TRACKS={daily:ASSET+'audio/2. 일상.mp3',minigame:ASSET+'audio/MiniGame-theme.mp3',harin:ASSET+'audio/3. 서하린과의 일상.mp3'};
const CHARACTER_PROFILES={
 harin:{name:'서하린',heightCm:165,image:'harin-standing.png'},
 harinEvening:{name:'서하린',heightCm:165,image:'harin-evening-standing.png'},
 minjae:{name:'강민재',heightCm:182,image:'minjae-standing.png'},
 boss:{name:'박태식',heightCm:176,image:'boss-standing.png'},
 sea:{name:'윤세아',heightCm:161,image:'sea-standing.png'},
 nanabot:{name:'나나봇',heightCm:110,image:'nanabot-standing.png',scale:.52,defaultPosition:'center'}
};
const CHARACTER_POSITIONS={farLeft:18,left:31,center:50,right:69,farRight:82};
const scenes=[
 {id:'intro',time:'09:00',speaker:'한도윤',text:'월요일 아침. 메일함 맨 위에 계약 종료 안내가 떠 있었다.\n남은 기간은 닷새. 정직원 전환 심사의 마지막 관문은 이번 주 최종 PT다.',bg:'office',bgm:'daily'},
 {id:'introResolve',time:'09:02',speaker:'한도윤',text:'지난 평가 때는 “선배의 도움으로 완성한 결과물”이라는 말을 들었다.\n이번만큼은 누구의 도움도 아닌, 내 실력으로 인정받고 싶었다.'},
 {id:'minjaeMorning',time:'09:05',speaker:'강민재',text:'일찍 왔네. 나만 긴장해서 잠 못 잔 줄 알았더니.\n우리 둘 다 심사 대상이지만, 그렇다고 너무 살벌하게 굴진 말자.',char:'minjae'},
 {id:'boss1',time:'09:08',speaker:'박태식',text:'한도윤 씨. 전환 과제는 우리 게임의 신규 유저 이탈률 개선안이야. 문제 원인, 개선안, 검증 방법까지 금요일에 발표해.',characters:[{id:'minjae',position:'left'},{id:'boss',position:'center'},{id:'harin',position:'right'}],activeCharacter:'boss'},
 {id:'boss2',time:'09:09',speaker:'박태식',text:'AI는 쓰되 AI 자랑은 하지 말고, 숫자는 확실한 것만. 그리고 발표는 눈에 들어오게. 중요한 건 결과니까.',characters:[{id:'minjae',position:'left'},{id:'boss',position:'center'},{id:'harin',position:'right'}],activeCharacter:'boss'},
 {id:'bossAfter',time:'09:10',speaker:'강민재',text:'결국 예쁘고 그럴듯하게 만들라는 뜻 아닌가?',characters:[{id:'minjae',position:'left'},{id:'harin',position:'right'}],activeCharacter:'minjae'},
 {id:'harinCorrection',time:'09:11',speaker:'서하린',text:'검증된 근거가 먼저라는 뜻이에요. 보기 좋은 건 그다음이고요.',characters:[{id:'minjae',position:'left'},{id:'harin',position:'right'}],activeCharacter:'harin'},
 {id:'harin1',time:'09:12',speaker:'서하린',text:'이번 PT는 제가 중간 검토할게요. 혼자 준비하는 과제 아니에요.',char:'harin',choiceKey:'firstSupport',choices:[
   {text:'감사합니다. 정리되면 바로 공유드릴게요.',delta:{trust:2},reply:'“좋아요. 판단 근거까지 같이 남겨두면 더 빨리 볼 수 있어요.”'},
   {text:'초안 정도는 혼자 만들어보겠습니다.',delta:{work:1,trust:-1},reply:'“초안까지는 좋아요. 다만 혼자 만든다는 말과 혼자 버틴다는 말은 다르니까요.”'},
   {text:'혹시 부장님이 저를 못 미더워하신 건가요?',delta:{affection:1,trust:1},reply:'“부장님 때문 아니에요. 혼자 하다가 망가지는 사람을 많이 봐서 그래요.”'}]},
 {id:'harinThought',time:'09:13',speaker:'한도윤',text:'고마운 말인데도 마음 한구석이 불편했다. 도움을 받으면 또 내 결과가 아니라고 평가받을 것 같았다.'},
 {id:'messageNotice',time:'09:15',speaker:'시스템',text:'PT 전환과제 TF에 새 메시지가 도착했습니다.\n하단의 MESSENGER 탭에서 확인하세요.',char:'harin',requireMessage:true,notification:'pt-first'},
 {id:'afterMessage',time:'09:22',speaker:'서하린',text:'좋아요. 요구사항은 기록해 두죠. 나중에 말이 달라지면 원문이 제일 정확하니까요.',char:'harin',clue:'박태식의 최초 지시: 유저 경험 중심·검증된 수치 사용'},
 {id:'workPlan',time:'09:30',speaker:'서하린',text:'금요일까지 시간이 많지 않아요. 오늘 어떤 자료부터 확인할 생각이에요?',char:'harin',choiceKey:'workPlan',choices:[
   {text:'신규 유저가 이탈하는 구간부터 조사한다.',delta:{work:1},clue:'조사 자료: 구간별 이탈 데이터',reply:'“좋아요. 먼저 어디에서 빠져나가는지 알아야 개선안도 설득력이 생기죠.”'},
   {text:'경쟁 게임의 신규 유저 경험부터 조사한다.',delta:{work:1},clue:'조사 자료: 경쟁 게임 사례',reply:'“비교 기준을 잡는 것도 좋겠네요. 그대로 따라 하지는 말고 이유를 찾아봐요.”'},
   {text:'눈에 띄는 AI 기능 아이디어부터 정리한다.',delta:{work:0,trust:1},clue:'조사 자료: AI 기능 아이디어',reply:'“아이디어는 괜찮지만, 부장님이 말한 건 AI 자체보다 유저 경험에 가까웠어요.”'}]},
 {id:'researchStart',time:'10:00',speaker:'한도윤',text:'하린이 공유한 사내 자료실에서 이탈 데이터, 고객 리뷰, 기존 안내 문서를 차례로 열었다.'},
 {id:'researchData',time:'10:06',speaker:'시스템',text:'자료 조사 결과\n· 초반 안내가 길다는 의견이 많다.\n· 첫 전투에 진입하기 전에 이탈하는 유저가 많다.',clue:'조사 결과: 긴 초반 안내·늦은 첫 전투'},
 {id:'fileVersions',time:'10:14',speaker:'한도윤',text:'신규유저_개선안, 신규유저_개선안_수정, 신규유저_개선안_최종, 신규유저_개선안_최종진짜…\n비슷한 이름의 문서가 너무 많았다.',clue:'자료실에 비슷한 이름의 문서가 여러 개 존재'},
 {id:'fileJoke',time:'10:16',speaker:'서하린',text:'웃지 마세요. 금요일이면 도윤 씨 폴더도 저렇게 될 수 있어요.',char:'harin'},
 {id:'fileJokeReply',time:'10:17',speaker:'한도윤',text:'저는 파일명 정리 잘합니다.',char:'harin'},
 {id:'fileJokeEnd',time:'10:18',speaker:'서하린',text:'그 말도 금요일에 확인해볼게요.',char:'harin'},
 {id:'coffeeSetup',time:'10:28',speaker:'강민재',text:'부장님이 15분 뒤에 중간 회의 잡았어. 난 회의실 켤 테니까, 커피 세 잔만 부탁한다.',characters:[{id:'minjae',position:'left'},{id:'harin',position:'right'}],activeCharacter:'minjae'},
 {id:'coffeeIntro',time:'10:30',speaker:'서하린',text:'주문은 적어두는 게 안전한데… 도윤 씨 표정을 보니 그냥 외우려는 것 같네요.',characters:[{id:'minjae',position:'left'},{id:'harin',position:'right'}],activeCharacter:'harin',startCoffee:true},
 {id:'coffeeResult',time:'10:45',speaker:'박태식',text:'커피 고마워. 요구사항도 지금처럼 놓치지 말고. 예상 수치는 검증된 것만 써.',characters:[{id:'minjae',position:'left'},{id:'boss',position:'center'},{id:'harin',position:'right'}],activeCharacter:'boss'},
 {id:'bossVerbal',time:'11:00',speaker:'박태식',text:'아, 발표는 너무 딱딱하지 않게 해. 눈에 들어오게. 아까 말한 느낌 알지?',characters:[{id:'boss',position:'left'},{id:'harin',position:'right'}],activeCharacter:'boss'},
 {id:'harinInterpret',time:'11:02',speaker:'서하린',text:'방금 말씀은 표현 방식에 대한 이야기겠죠? 방향을 바꾸라는 건 아닐 거예요.',characters:[{id:'boss',position:'left'},{id:'harin',position:'right'}],activeCharacter:'harin',clue:'박태식의 구두 지시: 발표를 눈에 들어오게'},
 {id:'lunchMinjae',time:'12:20',speaker:'강민재',text:'너 정직원 되면 내가 떨어지는 구조 같아서 좀 짜증 나긴 하는데, 그렇다고 네가 망하길 바라는 건 아니거든.',char:'minjae'},
 {id:'lunchArchive',time:'12:22',speaker:'강민재',text:'작년 신규 유저 개선 발표가 자료실 구버전 폴더에 있어. 방향 잡을 때 참고는 될 거야. 파일명이 비슷하니까 잘 보고 열어.',char:'minjae',clue:'강민재가 과거 발표 자료와 구버전 폴더의 위치를 알고 있음'},
 {id:'direction',time:'13:30',speaker:'한도윤',text:'조사 자료를 바탕으로 PT의 핵심 개선 방향을 정해야 한다.',choiceKey:'direction',choices:[
   {text:'긴 튜토리얼을 줄이고 핵심 행동부터 경험하게 한다.',delta:{work:2},clue:'PT 방향: 튜토리얼 단축',reply:'조사 결과와 가장 직접적으로 연결되는 방향이다. 문제와 개선안의 흐름이 선명해졌다.'},
   {text:'첫 전투까지 상황별 가이드를 제공한다.',delta:{work:1,trust:1},clue:'PT 방향: 상황별 가이드',reply:'필요한 순간에만 도움을 제공하면 안내 피로를 줄일 수 있다. 서하린도 고개를 끄덕였다.'},
   {text:'AI가 플레이 상황에 맞는 도움말을 추천한다.',delta:{work:1},clue:'PT 방향: AI 맞춤 도움말',reply:'눈에 띄는 아이디어지만 AI 자체가 목적처럼 보이지 않도록 사용자 근거를 더 보강해야 한다.'}]},
 {id:'nanaIntro',time:'15:00',speaker:'나나봇',text:'조사 내용을 발표용 문장으로 정리할 수 있습니다! 더 읽기 쉬운 표현이 발견되면 문장을 추천해 드릴게요.',char:'nanabot'},
 {id:'nanaExample',time:'15:01',speaker:'나나봇',text:'원문: “첫 전투 이전 구간에서 신규 유저 이탈률이 높다.”\n추천: “신규 유저의 첫 경험을 혁신해 이탈 가능성을 최소화합니다.”',characters:[{id:'nanabot',position:'left'},{id:'harin',position:'right'}],activeCharacter:'nanabot'},
 {id:'nanaWarning',time:'15:02',speaker:'서하린',text:'보기는 좋은데, 수치와 근거가 사라졌네요. 편한 기능일수록 원문과 비교해야 해요.',characters:[{id:'nanabot',position:'left'},{id:'harin',position:'right'}],activeCharacter:'harin'},
 {id:'nanaChoice',time:'15:04',speaker:'시스템',text:'PT 초안을 어떤 방식으로 정리할까?',choiceKey:'nanaUse',choices:[
   {text:'핵심 문장은 직접 작성하고 나나봇은 문장만 다듬게 한다.',delta:{work:1,trust:1},clue:'나나봇 자동 정리 활성화',reply:'핵심 의미는 직접 유지하고, 표현을 다듬는 작업만 나나봇에 맡겼다.'},
   {text:'조사 자료 전체를 나나봇으로 자동 요약한다.',delta:{work:2},clue:'나나봇 자동 요약 활성화',reply:'나나봇이 조사 자료를 빠르게 발표용 문장으로 정리했다. 지금은 꽤 편리해 보인다.'}]},
 {id:'draft',time:'16:30',speaker:'시스템',text:'PT 기획 초안 v0.1 완성\n문제 정의 · 조사 근거 · 개선 방향 · 검증 방법이 정리되었습니다.\n파일명: 신규유저_이탈개선_PT_v0.1',clue:'Day 1 원본 초안: 신규유저_이탈개선_PT_v0.1'},
 {id:'harinReview',time:'17:20',speaker:'서하린',text:'문제 정의와 조사 근거는 좋아요. 다만 검증 방법은 조금 더 구체화해야 하고, 나나봇이 다듬은 문장은 원문에서 멀어진 부분이 있어요.',char:'harin'},
 {id:'versionReview',time:'17:21',speaker:'서하린',text:'파일명이 v0.1이면 합격. “최종”이라고 썼으면 제가 지웠어요. 이 팀, 최종본이 너무 많거든요.',char:'harin'},
 {id:'finalJoke',time:'17:22',speaker:'한도윤',text:'설마 제 폴더까지 최종본이 여러 개가 되겠어요?',char:'harin'},
 {id:'finalJoke2',time:'17:23',speaker:'서하린',text:'그 말을 한 사람들 문서함에는 보통 최종본이 세 개씩 있어요.',char:'harin'},
 {id:'originalWarning',time:'17:24',speaker:'서하린',text:'도윤 씨가 만든 원본은 따로 보관하세요. 나중에 누구 말이 맞았는지 확인하려면 처음 기록이 필요하니까.',char:'harin',clue:'서하린의 경고: 정상 원본과 최초 기록을 따로 보관할 것'},
 {id:'eveningLead',time:'20:18',speaker:'한도윤',text:'퇴근 후, 집에 들러 옷을 갈아입고 늦은 저녁을 사러 동네 편의점에 들어갔다.\n음료 냉장고 앞에서 익숙한 목소리가 들렸다.',bg:'store',bgm:'harin',location:'동네 편의점 · 저녁'},
 {id:'eveningReveal',time:'20:18',speaker:'서하린',text:'……한도윤 씨?',bg:'store',location:'동네 편의점 · 저녁'},
 {id:'eveningCG',time:'20:18',speaker:'서하린',text:'회사 밖에서는 못 알아보는 타입이에요?',bg:'store',cg:'day1-harin-convenience-cg-v2.png',cgTitle:'퇴근 후, 뜻밖의 이웃',cinematicDelay:3000,location:'동네 편의점 · 저녁'},
 {id:'neighborSurprise',time:'20:19',speaker:'서하린',text:'그런데… 설마 도윤 씨도 이 근처에 살아요?',bg:'store',char:'harinEvening',location:'동네 편의점 · 저녁'},
 {id:'neighborConfirm',time:'20:20',speaker:'한도윤',text:'저 앞 오피스텔이요. 선배도 이 동네인 줄은 몰랐습니다.',bg:'store',char:'harinEvening',location:'동네 편의점 · 저녁'},
 {id:'dinnerCheck',time:'20:21',speaker:'서하린',text:'그런데 저녁이 삼각김밥 하나예요? 퇴근하고도 혼자 고생하는 건 여전하네요.',bg:'store',char:'harinEvening',location:'동네 편의점 · 저녁'},
 {id:'harinStore',time:'20:23',speaker:'서하린',text:'오늘도 왜 그렇게 혼자 끝내려고 했어요?',bg:'store',char:'harinEvening',location:'동네 편의점 · 저녁',choiceKey:'eveningTrust',choices:[
   {text:'선배가 같이 봐주시면 든든할 것 같아요.',delta:{affection:1,trust:2},reply:'서하린은 작게 웃었다. “그 말, 내일도 기억하세요.”'},
   {text:'이번에는 제 실력으로 인정받고 싶었습니다.',delta:{affection:1,trust:1},reply:'“도와달라는 말이 실력이 없다는 뜻은 아니에요. 적어도 저는 그렇게 평가하지 않아요.”'},
   {text:'회사에서도 이웃인 걸 모른 척해야 합니까?',delta:{affection:2},reply:'“그건… 도윤 씨가 아침마다 지각만 안 하면 생각해볼게요.” 하린이 장난스럽게 웃었다.'},
   {text:'제가 맡은 일이니 혼자 해보겠습니다.',delta:{work:1,trust:-1},reply:'“책임감이랑 혼자 버티는 건 달라요.” 서하린의 표정이 조금 굳었다.'}]},
 {id:'eveningAdvice',time:'20:24',speaker:'서하린',text:'도와달라는 말이 실력이 없다는 뜻은 아니에요. 오늘 만든 v0.1은 꼭 따로 보관하고, 내일은 숫자부터 같이 검증해요.',bg:'store',char:'harinEvening',location:'동네 편의점 · 저녁'},
 {id:'eveningMessage',time:'20:25',speaker:'시스템',text:'서하린에게 새 개인 메시지가 도착했습니다.\n“내일 오전에 숫자부터 같이 검증해요. 그리고 오늘 만든 v0.1, 절대 덮어쓰지 말고요.”',bg:'store',location:'동네 편의점 · 저녁',notification:'harin-evening'},
 {id:'end',time:'20:27',speaker:'시스템',text:'DAY 1 완료\n정상 원본 신규유저_이탈개선_PT_v0.1이 저장되었습니다.\n아직 파일에 이상 현상은 없습니다.',bg:'store',location:'동네 편의점 · 저녁',end:true}
];
const state={version:3,index:0,sceneId:'intro',work:0,stamina:5,affection:0,trust:0,readMessage:false,clues:[],unreadClues:false,coffeeDone:false,decisions:{},seenNotifications:{}};
const $=s=>document.querySelector(s);const audio=$('#bgm');let currentTrack='';let fadeToken=0;let currentRoom='',cinematicLocked=false,cinematicTimer;
const refs={stage:$('#stage'),characterLayer:$('#character-layer'),cg:$('#event-cg'),cgImage:$('#event-cg-image'),dialogueCard:$('#dialogue-card'),messenger:$('#messenger'),messageSfx:$('#message-sfx'),clock:$('#clock'),speaker:$('#speaker'),dialogue:$('#dialogue'),stageChoices:$('#stage-choices'),next:$('#next'),toast:$('#toast'),soundPrompt:$('#sound-prompt')};
const statDescriptions={
 work:'PT 준비와 업무 수행 성과를 나타냅니다. 높은 업무력은 업무 평가와 최종 결과에 유리하게 작용합니다.',
 stamina:'하루 동안 업무를 수행할 수 있는 여유를 나타냅니다. 실수하거나 무리하면 감소할 수 있습니다.',
 affection:'서하린과의 감정적 거리를 나타냅니다. 대화 선택과 관계 중심 결과에 영향을 줍니다.',
 trust:'회사 팀이 플레이어를 업무 파트너로서 얼마나 신뢰하는지 나타냅니다. 팀 내 협업과 업무 관련 결과에 영향을 줍니다.'
};
const statHelpPopover=$('#stat-help-popover');let activeStatHelp=null;
function closeStatHelp({restoreFocus=false}={}){if(!activeStatHelp)return;const button=activeStatHelp;activeStatHelp=null;button.setAttribute('aria-expanded','false');button.removeAttribute('aria-describedby');statHelpPopover.hidden=true;if(restoreFocus)button.focus()}
function openStatHelp(button){closeStatHelp();activeStatHelp=button;button.setAttribute('aria-expanded','true');button.setAttribute('aria-describedby','stat-help-popover');statHelpPopover.textContent=statDescriptions[button.dataset.stat];statHelpPopover.hidden=false;const rect=button.getBoundingClientRect(),popoverRect=statHelpPopover.getBoundingClientRect(),gap=8;let left=Math.min(innerWidth-popoverRect.width-12,Math.max(12,rect.left+rect.width/2-popoverRect.width/2));let top=rect.bottom+gap;if(top+popoverRect.height>innerHeight-12)top=Math.max(12,rect.top-popoverRect.height-gap);statHelpPopover.style.left=`${left}px`;statHelpPopover.style.top=`${top}px`}
function savedState(){return {...state,version:3,sceneId:(scenes[state.index]||scenes[0]).id,savedAt:new Date().toISOString()}}
function save(){localStorage.setItem('nan-day1-save',JSON.stringify(savedState()));toast('진행 상황을 저장했습니다.')}
function load(){try{const saved=JSON.parse(localStorage.getItem('nan-day1-save'))||{};if(saved.version!==3)return;Object.assign(state,saved);const savedIndex=scenes.findIndex(scene=>scene.id===saved.sceneId);state.index=savedIndex>=0?savedIndex:0;state.decisions=state.decisions||{};state.clues=state.clues||[];state.unreadClues=!!state.unreadClues;state.seenNotifications=state.seenNotifications||{}}catch{}}
function getBgmVolume(){try{const s=JSON.parse(localStorage.getItem('nan-game-settings-v1'))||{};if(s.masterMuted||s.bgmMuted)return 0;return Math.min(1,Math.max(0,((s.masterVolume??80)/100)*((s.bgmVolume??70)/100)))}catch{return .56}}
function fade(to,ms,token){const from=audio.volume,start=performance.now();return new Promise(resolve=>{function step(now){if(token!==fadeToken)return resolve();const p=Math.min(1,(now-start)/ms);audio.volume=from+(to-from)*p;if(p<1)requestAnimationFrame(step);else resolve()}requestAnimationFrame(step)})}
async function unlockAudio(){audio.volume=getBgmVolume();try{await audio.play();refs.soundPrompt.classList.add('hidden');$('#mute').classList.remove('muted');return true}catch{refs.soundPrompt.classList.remove('hidden');return false}}
async function playBgm(name){if(!name)return;if(name===currentTrack){await unlockAudio();return}const token=++fadeToken;if(currentTrack&&!audio.paused)await fade(0,650,token);if(token!==fadeToken)return;audio.src=TRACKS[name];audio.load();audio.volume=getBgmVolume();currentTrack=name;if(await unlockAudio())await fade(getBgmVolume(),500,token)}
function getSfxVolume(){try{const s=JSON.parse(localStorage.getItem('nan-game-settings-v1'))||{};if(s.masterMuted||s.sfxMuted)return 0;return Math.min(1,Math.max(0,((s.masterVolume??80)/100)*((s.sfxVolume??80)/100)))}catch{return .64}}
function playMessageSfx(){refs.messageSfx.volume=getSfxVolume();refs.messageSfx.currentTime=0;refs.messageSfx.play().catch(()=>{})}
function toast(text){refs.toast.textContent=text;refs.toast.classList.add('show');setTimeout(()=>refs.toast.classList.remove('show'),1700)}
function syncStats(){for(const id of ['work','stamina'])$('#'+id).textContent=state[id];$('#sys-work').textContent=state.work;$('#sys-stamina').textContent=state.stamina;$('#affection').textContent=state.affection;$('#trust').textContent=state.trust}
function renderClues(){const list=$('#clue-list'),badge=$('#clue-new');$('#clue-count').textContent=state.clues.length;badge.hidden=!state.unreadClues;if(!state.clues.length){list.innerHTML='<div class="clue-empty"><span>◇</span><strong>아직 기록된 단서가 없습니다</strong><p>대화와 자료를 조사하면 중요한 정보가 여기에 정리됩니다.</p></div>';return}list.innerHTML=state.clues.slice().reverse().map((x,index)=>`<article class="clue-card"><small>CLUE ${String(state.clues.length-index).padStart(2,'0')}</small>${x}</article>`).join('')}
function addClue(text){if(!text||state.clues.includes(text))return;state.clues.push(text);state.unreadClues=!$('#clues-view').classList.contains('active');renderClues();toast('단서가 기록되었습니다.')}
function setTab(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));if(name==='clues-view'){state.unreadClues=false;renderClues();saveSilently()}}
function renderCharacters(scene){const characters=scene.characters||(scene.char?[{id:scene.char}]:[]),active=scene.activeCharacter||scene.char||characters[0]?.id;refs.characterLayer.innerHTML='';refs.characterLayer.dataset.count=characters.length;characters.forEach((entry,index)=>{const profile=CHARACTER_PROFILES[entry.id];if(!profile)return;const image=document.createElement('img');const position=entry.position||profile.defaultPosition||(characters.length===1?'right':characters.length===2?(index===0?'left':'right'):index===0?'left':index===1?'center':'right');image.className=`character character-${entry.id} visible ${entry.id===active?'speaking':'listening'}`;image.src=ASSET+`characters/${profile.image}`;image.alt=profile.name;image.style.setProperty('--position-x',CHARACTER_POSITIONS[position]??CHARACTER_POSITIONS.right);image.style.setProperty('--sprite-height',`${84*(profile.heightCm/182)*(profile.scale||1)}cqh`);image.onerror=()=>image.remove();refs.characterLayer.appendChild(image)})}
function resetCinematic(){clearTimeout(cinematicTimer);cinematicLocked=false;refs.stage.classList.remove('cinematic-only','cinematic-ready')}
function startCinematic(delay){cinematicLocked=true;refs.stage.classList.add('cinematic-only');refs.next.disabled=true;cinematicTimer=setTimeout(()=>{cinematicLocked=false;refs.stage.classList.add('cinematic-ready');refs.next.disabled=false},delay)}
function notifyMessage(id){if(!id||state.seenNotifications[id])return;state.seenNotifications[id]=true;refs.messenger.classList.remove('message-arrived');void refs.messenger.offsetWidth;refs.messenger.classList.add('message-arrived');const target=id==='pt-first'?$('#chat-pt'):$('#chat-harin');target?.classList.add('unread-pulse');playMessageSfx();toast(id==='pt-first'?'PT 전환과제 TF에 새 메시지가 도착했습니다.':'서하린에게 새 메시지가 도착했습니다.');setTimeout(()=>refs.messenger.classList.remove('message-arrived'),1900)}
function unlockCg(scene){try{const saved=JSON.parse(localStorage.getItem('nan-unlocked-cgs-v1'))||[],archive=saved.filter(entry=>typeof entry==='object'&&entry?.id!==scene.cg);archive.push({id:scene.cg,image:`assets/CG/${scene.cg}`,day:`DAY 1 · ${scene.time}`,title:scene.cgTitle||scene.location||'기록된 장면'});localStorage.setItem('nan-unlocked-cgs-v1',JSON.stringify(archive))}catch{}}
function render(){const s=scenes[state.index]||scenes[0];state.sceneId=s.id;refs.clock.textContent=s.time;refs.speaker.textContent=s.speaker;refs.dialogue.textContent=s.text;refs.next.disabled=!!s.requireMessage&&!state.readMessage;refs.next.textContent=s.end?'타이틀로　›':'다음　›';renderMessages();
 resetCinematic();
 if(s.bg)refs.stage.style.backgroundImage=`url('${ASSET}backgrounds/${s.bg==='office'?'day1-office.png':'day1-convenience-store.png'}')`;$('#scene-label').textContent=s.location||(Number(s.time.split(':')[0])>=12?'게임사업실 · 오후':'게임사업실 · 오전');
 if(s.cg){refs.cgImage.src=ASSET+`CG/${s.cg}`;refs.cgImage.alt=s.cgTitle||'스토리 이벤트 CG';refs.cg.classList.add('show');refs.cg.setAttribute('aria-hidden','false');refs.stage.classList.add('cg-active');unlockCg(s)}else{refs.cg.classList.remove('show');refs.cg.setAttribute('aria-hidden','true');refs.stage.classList.remove('cg-active')}
 renderCharacters(s);
 if(s.bgm)playBgm(s.bgm);if(s.clue)addClue(s.clue);refs.stageChoices.innerHTML='';refs.stageChoices.classList.remove('show');refs.stage.classList.remove('choice-mode');
 if(s.requireMessage&&!state.readMessage){addStageChoice('확인했습니다. 요구사항을 기준으로 구성하겠습니다.',replyToMessage);refs.next.disabled=true}
 if(s.choices&&!state.decisions[s.choiceKey||s.id]){s.choices.forEach(c=>addStageChoice(c.text,()=>choose(c,s.choiceKey||s.id)));refs.next.disabled=true}
 if(s.cinematicDelay)startCinematic(s.cinematicDelay);if(s.notification)notifyMessage(s.notification);if(s.startCoffee&&!state.coffeeDone){startCoffee();return}syncStats();saveSilently()}
function addStageChoice(text,handler){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=handler;refs.stageChoices.appendChild(b);refs.stageChoices.classList.add('show');refs.stage.classList.add('choice-mode')}
function choose(c,key){const before={work:state.work,stamina:state.stamina,affection:state.affection,trust:state.trust};Object.entries(c.delta).forEach(([k,v])=>state[k]+=v);state.decisions[key]=c.text;if(c.clue)addClue(c.clue);refs.dialogue.textContent=c.reply;refs.stageChoices.innerHTML='';refs.stageChoices.classList.remove('show');refs.stage.classList.remove('choice-mode');refs.next.disabled=false;syncStats();showChoiceResult(c,before,key);saveSilently()}
let choiceResultTimer;
function showChoiceResult(c,before,key){const entries=Object.entries(c.delta).filter(([,v])=>v!==0);if(!entries.length)return;const names={work:'업무력',stamina:'체력',affection:'호감도',trust:'신뢰도'},icons={work:'◆',stamina:'♥',affection:'♡',trust:'◇'};$('#choice-result-title').textContent=key==='eveningTrust'?'서하린과의 관계가 변했습니다':'선택이 능력치에 반영되었습니다';$('#choice-result-list').innerHTML=entries.map(([k,v])=>`<article class="${v>0?'gain':'loss'}"><i>${icons[k]}</i><div><span>${names[k]}</span><small>${before[k]} → ${state[k]}</small></div><strong>${v>0?'+':''}${v}</strong></article>`).join('');const panel=$('#choice-result');panel.classList.remove('show');panel.setAttribute('aria-hidden','false');requestAnimationFrame(()=>panel.classList.add('show'));entries.forEach(([k])=>pulseStat(k));clearTimeout(choiceResultTimer);choiceResultTimer=setTimeout(()=>{panel.classList.remove('show');panel.setAttribute('aria-hidden','true')},3000)}
function pulseStat(key){const target=key==='affection'||key==='trust'?$('#'+key):$('#'+key);if(!target)return;target.classList.remove('stat-pulse');void target.offsetWidth;target.classList.add('stat-pulse')}
function replyToMessage(){state.readMessage=true;$('#chat-pt').classList.remove('unread-pulse');addClue('부장 메신저: 유저 경험 중심');renderMessages();refs.stageChoices.innerHTML='';refs.stageChoices.classList.remove('show');refs.stage.classList.remove('choice-mode');refs.dialogue.textContent='답장을 보냈다. 메신저에는 대화 기록이 남았다.';refs.next.disabled=false;saveSilently()}
function next(){if(cinematicLocked)return;const s=scenes[state.index];if(s.end){location.href='index.html';return}if(s.requireMessage&&!state.readMessage){toast('메신저에서 답장을 확인하세요.');return}state.index=Math.min(state.index+1,scenes.length-1);state.sceneId=scenes[state.index].id;setTab('messages-view');render()}
function renderMessages(){const box=$('#messages');const at=id=>state.index>=scenes.findIndex(s=>s.id===id),arrived=at('messageNotice'),personalArrived=at('eveningMessage');$('#chat-pt').hidden=!arrived;$('#chat-list-empty').hidden=arrived;$('#chat-harin').hidden=!personalArrived;$('#chat-minjae').hidden=true;if(!arrived){box.innerHTML='<div class="message-empty"><span>✦</span><b>아직 도착한 메시지가 없습니다</b><p>대화를 진행하면 업무 메시지가 여기에 기록됩니다.</p></div>';$('#pt-preview').textContent='아직 도착한 메시지가 없습니다';$('#pt-time').textContent='';$('#pt-unread').hidden=true;$('#unread').textContent='';return}let html='<article class="message"><b>박태식 부장</b><p>AI 기능보다 첫 7일의 유저 경험을 중심으로. 예상 수치는 검증된 것만 사용하세요.</p><small>09:14</small></article>',preview='박태식 부장: AI 기능보다 첫 7일의 유저 경험을 중심으로.',time='09:14';if(state.readMessage){html+='<article class="message me"><b>한도윤</b><p>확인했습니다. 요구사항을 기준으로 구성하겠습니다.</p><small>09:16</small></article>';preview='나: 확인했습니다. 요구사항을 기준으로 구성하겠습니다.';time='09:16'}if(at('researchStart')){html+='<article class="message"><b>서하린 사수</b><p>자료실에 이탈 데이터와 고객 리뷰를 공유했어요. 확인한 근거는 초안에 같이 남겨주세요.</p><small>09:58</small></article>';preview='서하린 사수: 자료실에 조사 자료를 공유했어요.';time='09:58'}if(at('nanaIntro')){html+='<article class="message"><b>나나봇</b><p>PT 작업 문서에 문장 추천 및 자동 정리 기능을 사용할 수 있습니다.</p><small>14:59</small></article>';preview='나나봇: 문장 추천 및 자동 정리를 사용할 수 있습니다.';time='14:59'}if(at('draft')){html+='<article class="message me"><b>한도윤</b><p>신규유저_이탈개선_PT_v0.1 초안 공유드립니다. 중간 검토 부탁드립니다.</p><small>16:31</small></article>';preview='나: PT v0.1 초안 공유드립니다.';time='16:31'}if(at('harinReview')){html+='<article class="message"><b>서하린 사수</b><p>v0.1 확인했어요. 방향은 괜찮습니다. 파일 버전 이름은 계속 유지해주세요.</p><small>17:18</small></article>';preview='서하린 사수: v0.1 확인했어요. 방향은 괜찮습니다.';time='17:18'}$('#pt-preview').textContent=preview;$('#pt-time').textContent=time;$('#pt-unread').hidden=state.readMessage||currentRoom==='pt';$('#unread').textContent=state.readMessage?'':'1';if(personalArrived){$('#chat-harin .chat-copy small').textContent='내일 오전에 숫자부터 같이 검증해요.';$('#chat-harin time').textContent='20:25'}if(currentRoom==='harin'&&personalArrived){box.innerHTML='<article class="message"><b>서하린 사수</b><p>내일 오전에 숫자부터 같이 검증해요. 그리고 오늘 만든 v0.1, 절대 덮어쓰지 말고요.</p><small>20:25</small></article>'}else if(currentRoom&&currentRoom!=='pt'){box.innerHTML='<div class="message-empty"><span>✦</span><b>아직 대화가 없습니다</b><p>새로운 개인 메시지가 도착하면 여기에 표시됩니다.</p></div>'}else box.innerHTML=html;box.scrollTop=box.scrollHeight}
const roomInfo={pt:{type:'PROJECT CHANNEL',title:'# PT 전환과제 TF',members:'<span>박</span><span>서</span><span>한</span>'},harin:{type:'DIRECT MESSAGE',title:'서하린 사수',members:'<span>서</span>'},minjae:{type:'DIRECT MESSAGE',title:'강민재 동기',members:'<span>강</span>'}};
function openChat(room){currentRoom=room;const info=roomInfo[room];$('#room-type').textContent=info.type;$('#room-title').textContent=info.title;$('#room-members').innerHTML=info.members;$('#chat-list').hidden=true;$('#chat-room').hidden=false;$(`#chat-${room}`)?.classList.remove('unread-pulse');if(room==='pt')$('#pt-unread').hidden=true;renderMessages()}
function closeChat(){currentRoom='';$('#chat-room').hidden=true;$('#chat-list').hidden=false}
const orders=[{name:'박태식',role:'부장',answer:'진한 아메리카노'},{name:'서하린',role:'사수',answer:'아이스 라테'},{name:'강민재',role:'동기',answer:'달콤한 믹스커피'}];let coffeeStep=0,score=0;
let coffeeTimer;
function startCoffee(){playBgm('minigame');$('#minigame').classList.add('active');$('#minigame-intro').hidden=false;$('#minigame-play').hidden=true;$('#minigame-result').hidden=true;$('#coffee-start').onclick=beginCoffeeMemory}
function beginCoffeeMemory(){coffeeStep=0;score=0;$('#minigame-intro').hidden=true;$('#minigame-play').hidden=false;$('#coffee-title').textContent='세 사람의 주문을 기억하세요';$('#coffee-controls').innerHTML='';$('#orders').innerHTML=orders.map((o,i)=>`<article class="order"><span>ORDER 0${i+1}</span><div class="order-avatar">${o.name[0]}</div><b>${o.name} <em>${o.role}</em></b><p>${o.answer}</p></article>`).join('');let left=5;$('#coffee-seconds').textContent=left;$('#coffee-help').textContent='이름과 직책을 확인하세요. 시간이 지나면 주문 카드가 사라집니다.';$('#coffee-countdown').classList.remove('hidden');$('#timer-track').classList.remove('hidden');$('#timer-fill').style.animation='none';requestAnimationFrame(()=>{$('#timer-fill').style.animation='coffee-timer 5s linear forwards'});clearInterval(coffeeTimer);coffeeTimer=setInterval(()=>{left--;$('#coffee-seconds').textContent=Math.max(0,left);if(left<=0){clearInterval(coffeeTimer);$('#orders').innerHTML='';askCoffee()}},1000)}
function askCoffee(){const o=orders[coffeeStep];$('#coffee-countdown').classList.add('hidden');$('#timer-track').classList.add('hidden');$('#coffee-title').innerHTML=`<span>${o.name} ${o.role}</span>의 커피는?`;$('#coffee-help').textContent=`누구의 주문인지 확인하고 선택하세요 · ${coffeeStep+1} / ${orders.length}`;const choices=orders.map(x=>x.answer).sort(()=>Math.random()-.5);$('#coffee-controls').innerHTML=choices.map((x,i)=>`<button><span>0${i+1}</span>${x}<i>›</i></button>`).join('');$('#coffee-controls').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.childNodes[1].textContent===o.answer)score++;coffeeStep++;coffeeStep<orders.length?askCoffee():finishCoffee()})}
function finishCoffee(){state.coffeeDone=true;let workDelta=0,staminaDelta=0,title='',summary='',icon='';if(score===3){workDelta=2;title='완벽하게 기억했습니다!';summary='모든 주문을 정확하게 전달해 팀의 분위기가 좋아졌습니다.';icon='✓'}else if(score===2){workDelta=1;title='제법 잘 기억했습니다!';summary='한 번의 실수는 있었지만 커피 심부름을 무사히 마쳤습니다.';icon='✓'}else{workDelta=-1;staminaDelta=-1;title='주문이 조금 헷갈렸습니다';summary='커피 주문을 놓쳐 업무 흐름과 체력이 조금 떨어졌습니다.';icon='!'}state.work+=workDelta;state.stamina+=staminaDelta;syncStats();saveSilently();$('#minigame-play').hidden=true;$('#minigame-result').hidden=false;$('#result-icon').textContent=icon;$('#result-icon').classList.toggle('fail',score<2);$('#result-kicker').textContent=score===3?'PERFECT CLEAR':score===2?'CLEAR':'TRY AGAIN';$('#result-title').textContent=title;$('#result-summary').textContent=summary;$('#result-score').textContent=`${score} / ${orders.length}`;$('#result-stats').innerHTML=resultStat('업무력',workDelta,state.work)+resultStat('체력',staminaDelta,state.stamina);$('#result-continue').onclick=closeCoffeeResult}
function resultStat(label,delta,total){const sign=delta>0?'+':'';const tone=delta>0?'up':delta<0?'down':'same';return `<article class="${tone}"><span>${label}</span><strong>${sign}${delta}</strong><small>현재 ${total}</small></article>`}
function closeCoffeeResult(){$('#minigame').classList.remove('active');playBgm('daily');state.index++;state.sceneId=scenes[state.index].id;render()}
function saveSilently(){localStorage.setItem('nan-day1-save',JSON.stringify(savedState()))}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('.chat-item').forEach(b=>b.onclick=()=>openChat(b.dataset.room));$('#chat-back').onclick=closeChat;refs.next.onclick=next;$('#save').onclick=save;$('#restart').onclick=()=>{localStorage.removeItem('nan-day1-save');location.href='game.html?new=1'};$('#mute').onclick=async()=>{if(audio.paused)await unlockAudio();else{audio.pause();$('#mute').classList.add('muted');refs.soundPrompt.classList.remove('hidden')}};refs.soundPrompt.onclick=unlockAudio;
document.querySelectorAll('.stat-help').forEach(button=>{button.addEventListener('mouseenter',()=>openStatHelp(button));button.addEventListener('mouseleave',()=>{if(activeStatHelp===button)closeStatHelp()});button.addEventListener('focus',()=>openStatHelp(button));button.addEventListener('blur',()=>{if(activeStatHelp===button)closeStatHelp()});button.addEventListener('click',event=>{event.stopPropagation();if(matchMedia('(hover: hover)').matches)return;if(activeStatHelp===button)closeStatHelp();else openStatHelp(button)})});statHelpPopover.addEventListener('click',event=>event.stopPropagation());document.addEventListener('click',()=>closeStatHelp());document.addEventListener('keydown',event=>{if(event.key==='Escape'&&activeStatHelp)closeStatHelp({restoreFocus:true})});window.addEventListener('resize',()=>closeStatHelp());document.addEventListener('scroll',()=>closeStatHelp(),true);
if(new URLSearchParams(location.search).has('new'))localStorage.removeItem('nan-day1-save');else load();renderMessages();renderClues();syncStats();render();document.addEventListener('pointerdown',unlockAudio,{once:true});document.addEventListener('keydown',unlockAudio,{once:true});
