const ASSET='assets/';
const TRACKS={daily:ASSET+'audio/2. 일상.mp3',minigame:ASSET+'audio/MiniGame-theme.mp3',harin:ASSET+'audio/3. 서하린과의 일상.mp3'};
const scenes=[
 {id:'intro',time:'09:00',speaker:'한도윤',text:'월요일 아침. 계약 종료까지 닷새.\n오늘, 정직원 전환 PT 과제가 공개된다. 이번만큼은 내 힘으로 끝내야 한다.',bg:'office',bgm:'daily'},
 {id:'boss1',time:'09:08',speaker:'박태식',text:'한도윤 씨. 전환 과제는 우리 게임의 신규 유저 이탈률 개선안이야. 문제 원인, 개선안, 검증 방법까지 금요일에 발표해.'},
 {id:'boss2',time:'09:09',speaker:'박태식',text:'AI도 적당히 활용하고. 기술 자랑으로 끝내지 말고 첫 7일의 유저 경험을 보여줘. 중요한 건 결과니까.'},
 {id:'harin1',time:'09:12',speaker:'서하린',text:'이번 PT는 제가 중간 검토할게요. 혼자 준비하는 과제 아니에요.',char:'harin'},
 {id:'harinThought',time:'09:13',speaker:'한도윤',text:'도움은 고맙지만, 내 평가에 다른 사람을 끌어들이는 게 마음 편하지만은 않았다.',char:'harin'},
 {id:'messageNotice',time:'09:15',speaker:'시스템',text:'PT 전환과제 TF에 새 메시지가 도착했습니다.\n하단의 MESSENGER 탭에서 확인하세요.',char:'harin',requireMessage:true},
 {id:'afterMessage',time:'09:22',speaker:'서하린',text:'좋아요. 요구사항은 기록해 두죠. 나중에 말이 달라지면 원문이 제일 정확하니까요.',char:'harin',clue:'박태식의 최초 지시: 유저 경험 중심·검증된 수치 사용'},
 {id:'workPlan',time:'09:30',speaker:'서하린',text:'금요일까지 시간이 많지 않아요. 오늘 어떤 자료부터 확인할 생각이에요?',char:'harin',choiceKey:'workPlan',choices:[
   {text:'신규 유저가 이탈하는 구간부터 조사한다.',delta:{work:1},clue:'조사 자료: 구간별 이탈 데이터',reply:'“좋아요. 먼저 어디에서 빠져나가는지 알아야 개선안도 설득력이 생기죠.”'},
   {text:'경쟁 게임의 신규 유저 경험부터 조사한다.',delta:{work:1},clue:'조사 자료: 경쟁 게임 사례',reply:'“비교 기준을 잡는 것도 좋겠네요. 그대로 따라 하지는 말고 이유를 찾아봐요.”'},
   {text:'눈에 띄는 AI 기능 아이디어부터 정리한다.',delta:{work:0,trust:1},clue:'조사 자료: AI 기능 아이디어',reply:'“아이디어는 괜찮지만, 부장님이 말한 건 AI 자체보다 유저 경험에 가까웠어요.”'}]},
 {id:'researchStart',time:'10:00',speaker:'한도윤',text:'사내 자료실에서 이탈 데이터, 고객 리뷰, 기존 안내 문서를 차례로 열었다.'},
 {id:'researchData',time:'10:06',speaker:'시스템',text:'자료 조사 결과\n· 초반 안내가 길다는 의견이 많다.\n· 첫 전투에 진입하기 전에 이탈하는 유저가 많다.',clue:'조사 결과: 긴 초반 안내·늦은 첫 전투'},
 {id:'fileVersions',time:'10:14',speaker:'한도윤',text:'신규유저_개선안, 신규유저_개선안_수정, 신규유저_개선안_최종… 비슷한 이름의 문서가 너무 많았다.\n회사 파일 이름이 다 그렇지 뭐.',clue:'자료실에 비슷한 이름의 문서가 여러 개 존재'},
 {id:'coffeeIntro',time:'10:30',speaker:'강민재',text:'회의 전에 커피 좀 부탁해. 취향은 딱 한 번만 알려줄 거야.',char:'minjae',startCoffee:true},
 {id:'coffeeResult',time:'10:45',speaker:'박태식',text:'커피 고마워. 요구사항도 지금처럼 놓치지 말고. 예상 수치는 검증된 것만 써.'},
 {id:'bossVerbal',time:'11:00',speaker:'박태식',text:'아, 발표는 너무 딱딱하지 않게 해. 눈에 들어오게. 어제 말한 느낌 알지?'},
 {id:'harinInterpret',time:'11:02',speaker:'서하린',text:'방금 말씀은 표현 방식에 대한 이야기겠죠? 방향을 바꾸라는 건 아닐 거예요.',char:'harin',clue:'박태식의 구두 지시: 발표를 눈에 들어오게'},
 {id:'direction',time:'13:30',speaker:'한도윤',text:'조사 자료를 바탕으로 PT의 핵심 개선 방향을 정해야 한다.',choiceKey:'direction',choices:[
   {text:'긴 튜토리얼을 줄이고 핵심 행동부터 경험하게 한다.',delta:{work:2},clue:'PT 방향: 튜토리얼 단축',reply:'조사 결과와 가장 직접적으로 연결되는 방향이다. 문제와 개선안의 흐름이 선명해졌다.'},
   {text:'첫 전투까지 상황별 가이드를 제공한다.',delta:{work:1,trust:1},clue:'PT 방향: 상황별 가이드',reply:'필요한 순간에만 도움을 제공하면 안내 피로를 줄일 수 있다. 서하린도 고개를 끄덕였다.'},
   {text:'AI가 플레이 상황에 맞는 도움말을 추천한다.',delta:{work:1},clue:'PT 방향: AI 맞춤 도움말',reply:'눈에 띄는 아이디어지만 AI 자체가 목적처럼 보이지 않도록 사용자 근거를 더 보강해야 한다.'}]},
 {id:'nanaIntro',time:'15:00',speaker:'나나봇',text:'조사 내용을 발표용 문장으로 정리할 수 있습니다! 더 읽기 쉬운 표현이 발견되면 문장을 추천해 드릴게요.'},
 {id:'nanaChoice',time:'15:02',speaker:'시스템',text:'PT 초안을 어떤 방식으로 정리할까?',choiceKey:'nanaUse',choices:[
   {text:'핵심 문장은 직접 작성하고 나나봇은 문장만 다듬게 한다.',delta:{work:1,trust:1},clue:'나나봇 자동 정리 활성화',reply:'핵심 의미는 직접 유지하고, 표현을 다듬는 작업만 나나봇에 맡겼다.'},
   {text:'조사 자료 전체를 나나봇으로 자동 요약한다.',delta:{work:2},clue:'나나봇 자동 요약 활성화',reply:'나나봇이 조사 자료를 빠르게 발표용 문장으로 정리했다. 지금은 꽤 편리해 보인다.'}]},
 {id:'draft',time:'16:30',speaker:'시스템',text:'PT 기획 초안 v0.1 완성\n문제 정의 · 조사 근거 · 개선 방향 · 검증 방법이 정리되었습니다.\n파일명: 신규유저_이탈개선_PT_v0.1',clue:'Day 1 원본 초안: 신규유저_이탈개선_PT_v0.1'},
 {id:'harinReview',time:'17:20',speaker:'서하린',text:'방향은 괜찮아요. 오늘은 여기까지 해도 돼요. 그리고 파일은 버전 이름 확실하게 붙여두세요. 이 팀, 최종본이 너무 많거든요.',char:'harin'},
 {id:'finalJoke',time:'17:21',speaker:'한도윤',text:'설마 최종본이 여러 개겠어요?',char:'harin'},
 {id:'finalJoke2',time:'17:22',speaker:'서하린',text:'그 말을 한 사람들 문서함에는 보통 최종본이 세 개씩 있어요.',char:'harin'},
 {id:'evening',time:'20:18',speaker:'한도윤',text:'퇴근길, 회사 앞 편의점에서 익숙한 뒷모습을 발견했다.',bg:'store',bgm:'harin'},
 {id:'harinStore',time:'20:19',speaker:'서하린',text:'오늘 자료, 생각보다 괜찮았어요. 그런데 또 혼자 다 하려고 했죠?',char:'harin',choiceKey:'eveningTrust',choices:[
   {text:'선배가 같이 봐주시면 든든할 것 같아요.',delta:{affection:1,trust:2},reply:'서하린은 작게 웃었다. “그 말, 내일도 기억하세요.”'},
   {text:'제가 맡은 일이니 혼자 해보겠습니다.',delta:{work:1,trust:-1},reply:'“책임감이랑 혼자 버티는 건 달라요.” 서하린의 표정이 조금 굳었다.'},
   {text:'심사 때문에 저랑 엮인 거 불편하지 않으세요?',delta:{affection:-1,trust:1},reply:'“그런 이유였으면 여기까지 기다리지도 않았어요.”'}]},
 {id:'end',time:'20:25',speaker:'시스템',text:'DAY 1 완료\n정직원 전환 PT 초안 v0.1이 저장되었습니다.\n나나봇의 문서 자동 정리가 활성화되어 있습니다.',char:'harin',end:true}
];
const state={index:0,work:0,stamina:5,affection:0,trust:0,readMessage:false,clues:[],coffeeDone:false,decisions:{}};
const $=s=>document.querySelector(s);const audio=$('#bgm');let currentTrack='';let fadeToken=0;let currentRoom='';
const refs={stage:$('#stage'),char:$('#character'),clock:$('#clock'),speaker:$('#speaker'),dialogue:$('#dialogue'),stageChoices:$('#stage-choices'),next:$('#next'),toast:$('#toast'),soundPrompt:$('#sound-prompt')};
function save(){localStorage.setItem('nan-day1-save',JSON.stringify({...state,savedAt:new Date().toISOString()}));toast('진행 상황을 저장했습니다.')}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('nan-day1-save'))||{});state.decisions=state.decisions||{}}catch{}}
function getBgmVolume(){try{const s=JSON.parse(localStorage.getItem('nan-game-settings-v1'))||{};if(s.masterMuted||s.bgmMuted)return 0;return Math.min(1,Math.max(0,((s.masterVolume??80)/100)*((s.bgmVolume??70)/100)))}catch{return .56}}
function fade(to,ms,token){const from=audio.volume,start=performance.now();return new Promise(resolve=>{function step(now){if(token!==fadeToken)return resolve();const p=Math.min(1,(now-start)/ms);audio.volume=from+(to-from)*p;if(p<1)requestAnimationFrame(step);else resolve()}requestAnimationFrame(step)})}
async function unlockAudio(){audio.volume=getBgmVolume();try{await audio.play();refs.soundPrompt.classList.add('hidden');$('#mute').classList.remove('muted');return true}catch{refs.soundPrompt.classList.remove('hidden');return false}}
async function playBgm(name){if(!name)return;if(name===currentTrack){await unlockAudio();return}const token=++fadeToken;if(currentTrack&&!audio.paused)await fade(0,650,token);if(token!==fadeToken)return;audio.src=TRACKS[name];audio.load();audio.volume=getBgmVolume();currentTrack=name;if(await unlockAudio())await fade(getBgmVolume(),500,token)}
function toast(text){refs.toast.textContent=text;refs.toast.classList.add('show');setTimeout(()=>refs.toast.classList.remove('show'),1700)}
function syncStats(){for(const id of ['work','stamina'])$('#'+id).textContent=state[id];$('#sys-work').textContent=state.work;$('#sys-stamina').textContent=state.stamina;$('#affection').textContent=state.affection;$('#trust').textContent=state.trust}
function addClue(text){if(!text||state.clues.includes(text))return;state.clues.push(text);$('#clue-list').innerHTML=state.clues.map(x=>`<article class="clue-card">📎 ${x}</article>`).join('');toast('단서가 기록되었습니다.')}
function setTab(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name))}
function render(){const s=scenes[state.index]||scenes[0];refs.clock.textContent=s.time;refs.speaker.textContent=s.speaker;refs.dialogue.textContent=s.text;refs.next.disabled=!!s.requireMessage&&!state.readMessage;refs.next.textContent=s.end?'타이틀로　›':'다음　›';renderMessages();
 if(s.bg)refs.stage.style.backgroundImage=`url('${ASSET}backgrounds/${s.bg==='office'?'day1-office.png':'day1-convenience-store.png'}')`;const eveningIndex=scenes.findIndex(x=>x.id==='evening');$('#scene-label').textContent=state.index>=eveningIndex?'회사 앞 편의점 · 저녁':Number(s.time.split(':')[0])>=12?'게임사업실 · 오후':'게임사업실 · 오전';
 if(s.char){refs.char.src=ASSET+`characters/${s.char}-standing.png`;refs.char.alt=s.char==='harin'?'서하린':'강민재'}else refs.char.removeAttribute('src');
 if(s.bgm)playBgm(s.bgm);if(s.clue)addClue(s.clue);refs.stageChoices.innerHTML='';refs.stageChoices.classList.remove('show');refs.stage.classList.remove('choice-mode');
 if(s.requireMessage&&!state.readMessage){addStageChoice('확인했습니다. 요구사항을 기준으로 구성하겠습니다.',replyToMessage);refs.next.disabled=true}
 if(s.choices&&!state.decisions[s.choiceKey||s.id]){s.choices.forEach(c=>addStageChoice(c.text,()=>choose(c,s.choiceKey||s.id)));refs.next.disabled=true}
 if(s.startCoffee&&!state.coffeeDone){startCoffee();return}syncStats();saveSilently()}
function addStageChoice(text,handler){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=handler;refs.stageChoices.appendChild(b);refs.stageChoices.classList.add('show');refs.stage.classList.add('choice-mode')}
function choose(c,key){const before={work:state.work,stamina:state.stamina,affection:state.affection,trust:state.trust};Object.entries(c.delta).forEach(([k,v])=>state[k]+=v);state.decisions[key]=c.text;if(c.clue)addClue(c.clue);refs.dialogue.textContent=c.reply;refs.stageChoices.innerHTML='';refs.stageChoices.classList.remove('show');refs.stage.classList.remove('choice-mode');refs.next.disabled=false;syncStats();showChoiceResult(c,before,key);saveSilently()}
let choiceResultTimer;
function showChoiceResult(c,before,key){const entries=Object.entries(c.delta).filter(([,v])=>v!==0);if(!entries.length)return;const names={work:'업무력',stamina:'체력',affection:'호감도',trust:'신뢰도'},icons={work:'◆',stamina:'♥',affection:'♡',trust:'◇'};$('#choice-result-title').textContent=key==='eveningTrust'?'서하린과의 관계가 변했습니다':'선택이 능력치에 반영되었습니다';$('#choice-result-list').innerHTML=entries.map(([k,v])=>`<article class="${v>0?'gain':'loss'}"><i>${icons[k]}</i><div><span>${names[k]}</span><small>${before[k]} → ${state[k]}</small></div><strong>${v>0?'+':''}${v}</strong></article>`).join('');const panel=$('#choice-result');panel.classList.remove('show');panel.setAttribute('aria-hidden','false');requestAnimationFrame(()=>panel.classList.add('show'));entries.forEach(([k])=>pulseStat(k));clearTimeout(choiceResultTimer);choiceResultTimer=setTimeout(()=>{panel.classList.remove('show');panel.setAttribute('aria-hidden','true')},3000)}
function pulseStat(key){const target=key==='affection'||key==='trust'?$('#'+key):$('#'+key);if(!target)return;target.classList.remove('stat-pulse');void target.offsetWidth;target.classList.add('stat-pulse')}
function replyToMessage(){state.readMessage=true;addClue('부장 메신저: 유저 경험 중심');renderMessages();refs.stageChoices.innerHTML='';refs.stageChoices.classList.remove('show');refs.stage.classList.remove('choice-mode');refs.dialogue.textContent='답장을 보냈다. 메신저에는 대화 기록이 남았다.';refs.next.disabled=false;saveSilently()}
function next(){const s=scenes[state.index];if(s.end){location.href='index.html';return}if(s.requireMessage&&!state.readMessage){toast('상단 화면에서 답장을 선택하세요.');return}state.index=Math.min(state.index+1,scenes.length-1);setTab('story');render()}
function renderMessages(){const box=$('#messages');const at=id=>state.index>=scenes.findIndex(s=>s.id===id),arrived=at('messageNotice');$('#chat-pt').hidden=!arrived;$('#chat-list-empty').hidden=arrived;$('#chat-harin').hidden=true;$('#chat-minjae').hidden=true;if(!arrived){box.innerHTML='<div class="message-empty"><span>✦</span><b>아직 도착한 메시지가 없습니다</b><p>대화를 진행하면 업무 메시지가 여기에 기록됩니다.</p></div>';$('#pt-preview').textContent='아직 도착한 메시지가 없습니다';$('#pt-time').textContent='';$('#pt-unread').hidden=true;$('#unread').textContent='';return}let html='<article class="message"><b>박태식 부장</b><p>AI 기능보다 첫 7일의 유저 경험을 중심으로. 예상 수치는 검증된 것만 사용하세요.</p><small>09:14</small></article>',preview='박태식 부장: AI 기능보다 첫 7일의 유저 경험을 중심으로.',time='09:14';if(state.readMessage){html+='<article class="message me"><b>한도윤</b><p>확인했습니다. 요구사항을 기준으로 구성하겠습니다.</p><small>09:16</small></article>';preview='나: 확인했습니다. 요구사항을 기준으로 구성하겠습니다.';time='09:16'}if(at('researchStart')){html+='<article class="message"><b>서하린 사수</b><p>자료실에 이탈 데이터와 고객 리뷰를 공유했어요. 확인한 근거는 초안에 같이 남겨주세요.</p><small>09:58</small></article>';preview='서하린 사수: 자료실에 조사 자료를 공유했어요.';time='09:58'}if(at('nanaIntro')){html+='<article class="message"><b>나나봇</b><p>PT 작업 문서에 문장 추천 및 자동 정리 기능을 사용할 수 있습니다.</p><small>14:59</small></article>';preview='나나봇: 문장 추천 및 자동 정리를 사용할 수 있습니다.';time='14:59'}if(at('draft')){html+='<article class="message me"><b>한도윤</b><p>신규유저_이탈개선_PT_v0.1 초안 공유드립니다. 중간 검토 부탁드립니다.</p><small>16:31</small></article>';preview='나: PT v0.1 초안 공유드립니다.';time='16:31'}if(at('harinReview')){html+='<article class="message"><b>서하린 사수</b><p>v0.1 확인했어요. 방향은 괜찮습니다. 파일 버전 이름은 계속 유지해주세요.</p><small>17:18</small></article>';preview='서하린 사수: v0.1 확인했어요. 방향은 괜찮습니다.';time='17:18'}$('#pt-preview').textContent=preview;$('#pt-time').textContent=time;$('#pt-unread').hidden=state.readMessage||currentRoom==='pt';$('#unread').textContent=state.readMessage?'':'1';box.innerHTML=currentRoom&&currentRoom!=='pt'?'<div class="message-empty"><span>✦</span><b>아직 대화가 없습니다</b><p>새로운 개인 메시지가 도착하면 여기에 표시됩니다.</p></div>':html;box.scrollTop=box.scrollHeight}
const roomInfo={pt:{type:'PROJECT CHANNEL',title:'# PT 전환과제 TF',members:'<span>박</span><span>서</span><span>한</span>'},harin:{type:'DIRECT MESSAGE',title:'서하린 사수',members:'<span>서</span>'},minjae:{type:'DIRECT MESSAGE',title:'강민재 동기',members:'<span>강</span>'}};
function openChat(room){currentRoom=room;const info=roomInfo[room];$('#room-type').textContent=info.type;$('#room-title').textContent=info.title;$('#room-members').innerHTML=info.members;$('#chat-list').hidden=true;$('#chat-room').hidden=false;if(room==='pt')$('#pt-unread').hidden=true;renderMessages()}
function closeChat(){currentRoom='';$('#chat-room').hidden=true;$('#chat-list').hidden=false}
const orders=[{name:'박태식',role:'부장',answer:'진한 아메리카노'},{name:'서하린',role:'사수',answer:'아이스 라테'},{name:'강민재',role:'동기',answer:'달콤한 믹스커피'}];let coffeeStep=0,score=0;
let coffeeTimer;
function startCoffee(){playBgm('minigame');$('#minigame').classList.add('active');$('#minigame-intro').hidden=false;$('#minigame-play').hidden=true;$('#minigame-result').hidden=true;$('#coffee-start').onclick=beginCoffeeMemory}
function beginCoffeeMemory(){coffeeStep=0;score=0;$('#minigame-intro').hidden=true;$('#minigame-play').hidden=false;$('#coffee-title').textContent='세 사람의 주문을 기억하세요';$('#coffee-controls').innerHTML='';$('#orders').innerHTML=orders.map((o,i)=>`<article class="order"><span>ORDER 0${i+1}</span><div class="order-avatar">${o.name[0]}</div><b>${o.name} <em>${o.role}</em></b><p>${o.answer}</p></article>`).join('');let left=5;$('#coffee-seconds').textContent=left;$('#coffee-help').textContent='이름과 직책을 확인하세요. 시간이 지나면 주문 카드가 사라집니다.';$('#coffee-countdown').classList.remove('hidden');$('#timer-track').classList.remove('hidden');$('#timer-fill').style.animation='none';requestAnimationFrame(()=>{$('#timer-fill').style.animation='coffee-timer 5s linear forwards'});clearInterval(coffeeTimer);coffeeTimer=setInterval(()=>{left--;$('#coffee-seconds').textContent=Math.max(0,left);if(left<=0){clearInterval(coffeeTimer);$('#orders').innerHTML='';askCoffee()}},1000)}
function askCoffee(){const o=orders[coffeeStep];$('#coffee-countdown').classList.add('hidden');$('#timer-track').classList.add('hidden');$('#coffee-title').innerHTML=`<span>${o.name} ${o.role}</span>의 커피는?`;$('#coffee-help').textContent=`누구의 주문인지 확인하고 선택하세요 · ${coffeeStep+1} / ${orders.length}`;const choices=orders.map(x=>x.answer).sort(()=>Math.random()-.5);$('#coffee-controls').innerHTML=choices.map((x,i)=>`<button><span>0${i+1}</span>${x}<i>›</i></button>`).join('');$('#coffee-controls').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.childNodes[1].textContent===o.answer)score++;coffeeStep++;coffeeStep<orders.length?askCoffee():finishCoffee()})}
function finishCoffee(){state.coffeeDone=true;let workDelta=0,staminaDelta=0,title='',summary='',icon='';if(score===3){workDelta=2;title='완벽하게 기억했습니다!';summary='모든 주문을 정확하게 전달해 팀의 분위기가 좋아졌습니다.';icon='✓'}else if(score===2){workDelta=1;title='제법 잘 기억했습니다!';summary='한 번의 실수는 있었지만 커피 심부름을 무사히 마쳤습니다.';icon='✓'}else{workDelta=-1;staminaDelta=-1;title='주문이 조금 헷갈렸습니다';summary='커피 주문을 놓쳐 업무 흐름과 체력이 조금 떨어졌습니다.';icon='!'}state.work+=workDelta;state.stamina+=staminaDelta;syncStats();saveSilently();$('#minigame-play').hidden=true;$('#minigame-result').hidden=false;$('#result-icon').textContent=icon;$('#result-icon').classList.toggle('fail',score<2);$('#result-kicker').textContent=score===3?'PERFECT CLEAR':score===2?'CLEAR':'TRY AGAIN';$('#result-title').textContent=title;$('#result-summary').textContent=summary;$('#result-score').textContent=`${score} / ${orders.length}`;$('#result-stats').innerHTML=resultStat('업무력',workDelta,state.work)+resultStat('체력',staminaDelta,state.stamina);$('#result-continue').onclick=closeCoffeeResult}
function resultStat(label,delta,total){const sign=delta>0?'+':'';const tone=delta>0?'up':delta<0?'down':'same';return `<article class="${tone}"><span>${label}</span><strong>${sign}${delta}</strong><small>현재 ${total}</small></article>`}
function closeCoffeeResult(){$('#minigame').classList.remove('active');playBgm('daily');state.index++;render()}
function saveSilently(){localStorage.setItem('nan-day1-save',JSON.stringify({...state,savedAt:new Date().toISOString()}))}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('.chat-item').forEach(b=>b.onclick=()=>openChat(b.dataset.room));$('#chat-back').onclick=closeChat;refs.next.onclick=next;$('#save').onclick=save;$('#restart').onclick=()=>{localStorage.removeItem('nan-day1-save');location.href='game.html?new=1'};$('#mute').onclick=async()=>{if(audio.paused)await unlockAudio();else{audio.pause();$('#mute').classList.add('muted');refs.soundPrompt.classList.remove('hidden')}};refs.soundPrompt.onclick=unlockAudio;
if(new URLSearchParams(location.search).has('new'))localStorage.removeItem('nan-day1-save');else load();renderMessages();syncStats();render();document.addEventListener('pointerdown',unlockAudio,{once:true});document.addEventListener('keydown',unlockAudio,{once:true});
